APP_STL := c++_static

APP_CPPFLAGS := -frtti -std=c++11 -fsigned-char -Wno-extern-c-compat
APP_CPPFLAGS += -DCC_ENABLE_CHIPMUNK_INTEGRATION=0
APP_CPPFLAGS += -DCC_USE_PHYSICS=0
APP_CPPFLAGS += -DCC_USE_3D_PHYSICS=0
APP_CPPFLAGS += -DCC_USE_NAVMESH=0
APP_CPPFLAGS += -DCC_ENABLE_BULLET_INTEGRATION=0
APP_CPPFLAGS += -DCC_USE_TIFF=0
APP_CPPFLAGS += -DCC_USE_WEBP=0
APP_CPPFLAGS += -DCC_ENABLE_SCRIPT_BINDING=0
APP_CPPFLAGS += -DCC_USE_3D=0

APP_LDFLAGS := -latomic

APP_ABI := armeabi-v7a
APP_SHORT_COMMANDS := true


ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif
